version: '2'
services:
  codiad:
    image: 'bitnami/codiad:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'codiad_data:/bitnami/codiad'
      - 'apache_data:/bitnami/apache'
volumes:
  codiad_data:
    driver: local
  apache_data:
    driver: local
