version: '2'

services:
  codiad:
    image: 'bitnami/codiad:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'codiad_data:/bitnami'
volumes:
  codiad_data:
    driver: local
