version: '2'

services:
  codiad:
    image: 'bitnami/codiad:2-ol-7'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'codiad_data:/bitnami'
volumes:
  codiad_data:
    driver: local
